/**
 * @file JSON persistence.
 *
 * Deliberately a flat-file store: the whole point of the demo is that a judge can
 * clone the repo and immediately see real data with no database to provision.
 * Committed seed data lives in `data/`; mutable run history lives in
 * `data/runtime/` which is gitignored and regenerated by `npm run seed`.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './config.js';

const DATA_DIR = join(ROOT, 'data');
const RUNTIME_DIR = join(DATA_DIR, 'runtime');

/**
 * @typedef {object} Target
 * @property {string}   id
 * @property {string}   name
 * @property {string}   category
 * @property {string}   url
 * @property {string}   collectorEnv
 * @property {string}   prompt
 * @property {string[]} expectedFields
 * @property {'low'|'medium'|'high'} signal
 * @property {string}   why
 */

/**
 * @typedef {object} ChangeEntry
 * @property {'feature'|'fix'|'breaking'|'chore'} type
 * @property {string} text
 */

/**
 * @typedef {object} Release
 * @property {string} version
 * @property {string} releasedAt   ISO date.
 * @property {string} [headline]
 * @property {ChangeEntry[]} entries
 */

/**
 * @typedef {object} Run
 * @property {string}  id
 * @property {string}  targetId
 * @property {string}  collectorId
 * @property {string}  startedAt      ISO timestamp.
 * @property {number}  durationMs
 * @property {'ok'|'degraded'|'failed'} status
 * @property {Release[]} releases
 * @property {string[]} missingFields  Expected fields absent from the payload.
 * @property {number}  recordCount
 * @property {number}  nullRate       0..1 — share of expected fields that came back empty.
 * @property {string}  [note]
 * @property {'fixture'|'live'} source
 */

/**
 * @typedef {object} CanonEvent
 * @property {string} id
 * @property {string} targetId
 * @property {string} at             ISO timestamp.
 * @property {'break'|'detect'|'heal_start'|'heal_done'|'recovered'} kind
 * @property {string} title
 * @property {string} detail
 * @property {number} [health]
 * @property {string} [collectorId]
 */

/**
 * @typedef {object} Database
 * @property {Run[]} runs
 * @property {CanonEvent[]} events
 */

/** @returns {void} */
function ensureRuntime() {
  if (!existsSync(RUNTIME_DIR)) mkdirSync(RUNTIME_DIR, { recursive: true });
}

/**
 * Read and parse a JSON file, returning a fallback when it is absent.
 *
 * @template T
 * @param {string} file
 * @param {T} fallback
 * @returns {T}
 */
function readJson(file, fallback) {
  try {
    if (!existsSync(file)) return fallback;
    return /** @type {T} */ (JSON.parse(readFileSync(file, 'utf8')));
  } catch {
    return fallback;
  }
}

/**
 * Atomically write JSON (write to a temp file, then rename) so a crash mid-write
 * can never leave a truncated database behind.
 *
 * @param {string} file
 * @param {unknown} value
 * @returns {void}
 */
function writeJson(file, value) {
  ensureRuntime();
  const tmp = `${file}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
  renameSync(tmp, file);
}

const RUNS_FILE = join(RUNTIME_DIR, 'runs.json');
const EVENTS_FILE = join(RUNTIME_DIR, 'events.json');

/**
 * Load the committed target registry.
 *
 * @returns {Target[]}
 */
export function getTargets() {
  const parsed = readJson(join(DATA_DIR, 'targets.json'), /** @type {{targets: Target[]}} */ ({ targets: [] }));
  return parsed.targets || [];
}

/**
 * Look up a single target by id.
 *
 * @param {string} id
 * @returns {Target | undefined}
 */
export function getTarget(id) {
  return getTargets().find((t) => t.id === id);
}

/** @returns {Run[]} */
export function getRuns() {
  return readJson(RUNS_FILE, /** @type {Run[]} */ ([]));
}

/** @returns {CanonEvent[]} */
export function getEvents() {
  return readJson(EVENTS_FILE, /** @type {CanonEvent[]} */ ([]));
}

/**
 * Replace the full run history. Used by the seeder.
 *
 * @param {Run[]} runs
 * @returns {void}
 */
export function saveRuns(runs) {
  writeJson(RUNS_FILE, runs);
}

/**
 * Replace the full event log. Used by the seeder.
 *
 * @param {CanonEvent[]} events
 * @returns {void}
 */
export function saveEvents(events) {
  writeJson(EVENTS_FILE, events);
}

/**
 * Append a run, newest last.
 *
 * @param {Run} run
 * @returns {Run}
 */
export function appendRun(run) {
  const runs = getRuns();
  runs.push(run);
  saveRuns(runs);
  return run;
}

/**
 * Append a canon event, newest last.
 *
 * @param {CanonEvent} event
 * @returns {CanonEvent}
 */
export function appendEvent(event) {
  const events = getEvents();
  events.push(event);
  saveEvents(events);
  return event;
}

/**
 * All runs for one target, oldest first.
 *
 * @param {string} targetId
 * @returns {Run[]}
 */
export function runsFor(targetId) {
  return getRuns().filter((r) => r.targetId === targetId);
}

/**
 * The most recent run for a target.
 *
 * @param {string} targetId
 * @returns {Run | undefined}
 */
export function latestRun(targetId) {
  const runs = runsFor(targetId);
  return runs.length ? runs[runs.length - 1] : undefined;
}

/** @returns {boolean} True when the runtime store has been seeded. */
export function isSeeded() {
  return existsSync(RUNS_FILE) && getRuns().length > 0;
}

/* ------------------------------------------------------------------
   Simulated breakage
   ------------------------------------------------------------------
   `npm run break <target>` records a break here. In fixture mode the
   pipeline consults this map and degrades the payload accordingly, which
   is how the self-healing loop is demonstrated without waiting for a real
   site to be redesigned. Healing clears the entry.
   ------------------------------------------------------------------ */

const BREAKS_FILE = join(RUNTIME_DIR, 'breaks.json');

/**
 * @typedef {object} BreakState
 * @property {import('./fixtures.js').BreakMode} mode
 * @property {string} at   ISO timestamp the break was introduced.
 */

/** @returns {Record<string, BreakState>} Keyed by target id. */
export function getBreaks() {
  return readJson(BREAKS_FILE, /** @type {Record<string, BreakState>} */ ({}));
}

/**
 * Record a simulated layout change for a target.
 *
 * @param {string} targetId
 * @param {import('./fixtures.js').BreakMode} mode
 * @param {string} at
 * @returns {void}
 */
export function setBreak(targetId, mode, at) {
  const breaks = getBreaks();
  breaks[targetId] = { mode, at };
  writeJson(BREAKS_FILE, breaks);
}

/**
 * Clear a target's break. Called when healing succeeds.
 *
 * @param {string} targetId
 * @returns {boolean} True if there was a break to clear.
 */
export function clearBreak(targetId) {
  const breaks = getBreaks();
  if (!(targetId in breaks)) return false;
  delete breaks[targetId];
  writeJson(BREAKS_FILE, breaks);
  return true;
}

/**
 * The active break mode for a target, if any.
 *
 * @param {string} targetId
 * @returns {import('./fixtures.js').BreakMode | null}
 */
export function breakFor(targetId) {
  return getBreaks()[targetId]?.mode ?? null;
}
